/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsDevelopmentRouteImport } from './routes/settings.development'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as NewTabIdRouteImport } from './routes/new-tab.$id'
import { Route as ChatChar123ChatIdChar125RouteImport } from './routes/chat.{-$chatId}'
import { Route as SettingsDevelopmentUpdateChannelRouteImport } from './routes/settings.development.update-channel'
import { Route as SettingsDevelopmentNetworkRouteImport } from './routes/settings.development.network'
import { Route as SettingsDevelopmentCustomChainsRouteImport } from './routes/settings.development.custom-chains'
import { Route as ProductIdChar123RouteChar125RouteImport } from './routes/product.$id.{-$route}'
import { Route as SettingsPrivacyPermissionsIndexRouteImport } from './routes/settings.privacy.permissions.index'
import { Route as SettingsPrivacyAppsIndexRouteImport } from './routes/settings.privacy.apps.index'
import { Route as SettingsPrivacyPermissionsPermissionIdRouteImport } from './routes/settings.privacy.permissions.$permissionId'
import { Route as SettingsPrivacyAppsProductIdRouteImport } from './routes/settings.privacy.apps.$productId'
import { Route as SettingsPrivacyPermissionsPermissionIdIndexRouteImport } from './routes/settings.privacy.permissions.$permissionId.index'
import { Route as SettingsPrivacyAppsProductIdIndexRouteImport } from './routes/settings.privacy.apps.$productId.index'
import { Route as SettingsPrivacyPermissionsPermissionIdProductIdRouteImport } from './routes/settings.privacy.permissions.$permissionId.$productId'
import { Route as SettingsPrivacyAppsProductIdPermissionIdRouteImport } from './routes/settings.privacy.apps.$productId.$permissionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevelopmentRoute = SettingsDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const NewTabIdRoute = NewTabIdRouteImport.update({
  id: '/new-tab/$id',
  path: '/new-tab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChar123ChatIdChar125Route =
  ChatChar123ChatIdChar125RouteImport.update({
    id: '/chat/{-$chatId}',
    path: '/chat/{-$chatId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsDevelopmentUpdateChannelRoute =
  SettingsDevelopmentUpdateChannelRouteImport.update({
    id: '/update-channel',
    path: '/update-channel',
    getParentRoute: () => SettingsDevelopmentRoute,
  } as any)
const SettingsDevelopmentNetworkRoute =
  SettingsDevelopmentNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => SettingsDevelopmentRoute,
  } as any)
const SettingsDevelopmentCustomChainsRoute =
  SettingsDevelopmentCustomChainsRouteImport.update({
    id: '/custom-chains',
    path: '/custom-chains',
    getParentRoute: () => SettingsDevelopmentRoute,
  } as any)
const ProductIdChar123RouteChar125Route =
  ProductIdChar123RouteChar125RouteImport.update({
    id: '/product/$id/{-$route}',
    path: '/product/$id/{-$route}',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsPrivacyPermissionsIndexRoute =
  SettingsPrivacyPermissionsIndexRouteImport.update({
    id: '/privacy/permissions/',
    path: '/privacy/permissions/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsPrivacyAppsIndexRoute =
  SettingsPrivacyAppsIndexRouteImport.update({
    id: '/privacy/apps/',
    path: '/privacy/apps/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsPrivacyPermissionsPermissionIdRoute =
  SettingsPrivacyPermissionsPermissionIdRouteImport.update({
    id: '/privacy/permissions/$permissionId',
    path: '/privacy/permissions/$permissionId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsPrivacyAppsProductIdRoute =
  SettingsPrivacyAppsProductIdRouteImport.update({
    id: '/privacy/apps/$productId',
    path: '/privacy/apps/$productId',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsPrivacyPermissionsPermissionIdIndexRoute =
  SettingsPrivacyPermissionsPermissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsPrivacyPermissionsPermissionIdRoute,
  } as any)
const SettingsPrivacyAppsProductIdIndexRoute =
  SettingsPrivacyAppsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsPrivacyAppsProductIdRoute,
  } as any)
const SettingsPrivacyPermissionsPermissionIdProductIdRoute =
  SettingsPrivacyPermissionsPermissionIdProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => SettingsPrivacyPermissionsPermissionIdRoute,
  } as any)
const SettingsPrivacyAppsProductIdPermissionIdRoute =
  SettingsPrivacyAppsProductIdPermissionIdRouteImport.update({
    id: '/$permissionId',
    path: '/$permissionId',
    getParentRoute: () => SettingsPrivacyAppsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/{-$chatId}': typeof ChatChar123ChatIdChar125Route
  '/new-tab/$id': typeof NewTabIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/development': typeof SettingsDevelopmentRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/product/$id/{-$route}': typeof ProductIdChar123RouteChar125Route
  '/settings/development/custom-chains': typeof SettingsDevelopmentCustomChainsRoute
  '/settings/development/network': typeof SettingsDevelopmentNetworkRoute
  '/settings/development/update-channel': typeof SettingsDevelopmentUpdateChannelRoute
  '/settings/privacy/apps/$productId': typeof SettingsPrivacyAppsProductIdRouteWithChildren
  '/settings/privacy/permissions/$permissionId': typeof SettingsPrivacyPermissionsPermissionIdRouteWithChildren
  '/settings/privacy/apps/': typeof SettingsPrivacyAppsIndexRoute
  '/settings/privacy/permissions/': typeof SettingsPrivacyPermissionsIndexRoute
  '/settings/privacy/apps/$productId/$permissionId': typeof SettingsPrivacyAppsProductIdPermissionIdRoute
  '/settings/privacy/permissions/$permissionId/$productId': typeof SettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/settings/privacy/apps/$productId/': typeof SettingsPrivacyAppsProductIdIndexRoute
  '/settings/privacy/permissions/$permissionId/': typeof SettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/chat/{-$chatId}': typeof ChatChar123ChatIdChar125Route
  '/new-tab/$id': typeof NewTabIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/development': typeof SettingsDevelopmentRouteWithChildren
  '/settings': typeof SettingsIndexRoute
  '/product/$id/{-$route}': typeof ProductIdChar123RouteChar125Route
  '/settings/development/custom-chains': typeof SettingsDevelopmentCustomChainsRoute
  '/settings/development/network': typeof SettingsDevelopmentNetworkRoute
  '/settings/development/update-channel': typeof SettingsDevelopmentUpdateChannelRoute
  '/settings/privacy/apps': typeof SettingsPrivacyAppsIndexRoute
  '/settings/privacy/permissions': typeof SettingsPrivacyPermissionsIndexRoute
  '/settings/privacy/apps/$productId/$permissionId': typeof SettingsPrivacyAppsProductIdPermissionIdRoute
  '/settings/privacy/permissions/$permissionId/$productId': typeof SettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/settings/privacy/apps/$productId': typeof SettingsPrivacyAppsProductIdIndexRoute
  '/settings/privacy/permissions/$permissionId': typeof SettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/{-$chatId}': typeof ChatChar123ChatIdChar125Route
  '/new-tab/$id': typeof NewTabIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/development': typeof SettingsDevelopmentRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/product/$id/{-$route}': typeof ProductIdChar123RouteChar125Route
  '/settings/development/custom-chains': typeof SettingsDevelopmentCustomChainsRoute
  '/settings/development/network': typeof SettingsDevelopmentNetworkRoute
  '/settings/development/update-channel': typeof SettingsDevelopmentUpdateChannelRoute
  '/settings/privacy/apps/$productId': typeof SettingsPrivacyAppsProductIdRouteWithChildren
  '/settings/privacy/permissions/$permissionId': typeof SettingsPrivacyPermissionsPermissionIdRouteWithChildren
  '/settings/privacy/apps/': typeof SettingsPrivacyAppsIndexRoute
  '/settings/privacy/permissions/': typeof SettingsPrivacyPermissionsIndexRoute
  '/settings/privacy/apps/$productId/$permissionId': typeof SettingsPrivacyAppsProductIdPermissionIdRoute
  '/settings/privacy/permissions/$permissionId/$productId': typeof SettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/settings/privacy/apps/$productId/': typeof SettingsPrivacyAppsProductIdIndexRoute
  '/settings/privacy/permissions/$permissionId/': typeof SettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/chat/{-$chatId}'
    | '/new-tab/$id'
    | '/settings/appearance'
    | '/settings/development'
    | '/settings/'
    | '/product/$id/{-$route}'
    | '/settings/development/custom-chains'
    | '/settings/development/network'
    | '/settings/development/update-channel'
    | '/settings/privacy/apps/$productId'
    | '/settings/privacy/permissions/$permissionId'
    | '/settings/privacy/apps/'
    | '/settings/privacy/permissions/'
    | '/settings/privacy/apps/$productId/$permissionId'
    | '/settings/privacy/permissions/$permissionId/$productId'
    | '/settings/privacy/apps/$productId/'
    | '/settings/privacy/permissions/$permissionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/chat/{-$chatId}'
    | '/new-tab/$id'
    | '/settings/appearance'
    | '/settings/development'
    | '/settings'
    | '/product/$id/{-$route}'
    | '/settings/development/custom-chains'
    | '/settings/development/network'
    | '/settings/development/update-channel'
    | '/settings/privacy/apps'
    | '/settings/privacy/permissions'
    | '/settings/privacy/apps/$productId/$permissionId'
    | '/settings/privacy/permissions/$permissionId/$productId'
    | '/settings/privacy/apps/$productId'
    | '/settings/privacy/permissions/$permissionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/chat/{-$chatId}'
    | '/new-tab/$id'
    | '/settings/appearance'
    | '/settings/development'
    | '/settings/'
    | '/product/$id/{-$route}'
    | '/settings/development/custom-chains'
    | '/settings/development/network'
    | '/settings/development/update-channel'
    | '/settings/privacy/apps/$productId'
    | '/settings/privacy/permissions/$permissionId'
    | '/settings/privacy/apps/'
    | '/settings/privacy/permissions/'
    | '/settings/privacy/apps/$productId/$permissionId'
    | '/settings/privacy/permissions/$permissionId/$productId'
    | '/settings/privacy/apps/$productId/'
    | '/settings/privacy/permissions/$permissionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ChatChar123ChatIdChar125Route: typeof ChatChar123ChatIdChar125Route
  NewTabIdRoute: typeof NewTabIdRoute
  ProductIdChar123RouteChar125Route: typeof ProductIdChar123RouteChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/development': {
      id: '/settings/development'
      path: '/development'
      fullPath: '/settings/development'
      preLoaderRoute: typeof SettingsDevelopmentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/new-tab/$id': {
      id: '/new-tab/$id'
      path: '/new-tab/$id'
      fullPath: '/new-tab/$id'
      preLoaderRoute: typeof NewTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/{-$chatId}': {
      id: '/chat/{-$chatId}'
      path: '/chat/{-$chatId}'
      fullPath: '/chat/{-$chatId}'
      preLoaderRoute: typeof ChatChar123ChatIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/development/update-channel': {
      id: '/settings/development/update-channel'
      path: '/update-channel'
      fullPath: '/settings/development/update-channel'
      preLoaderRoute: typeof SettingsDevelopmentUpdateChannelRouteImport
      parentRoute: typeof SettingsDevelopmentRoute
    }
    '/settings/development/network': {
      id: '/settings/development/network'
      path: '/network'
      fullPath: '/settings/development/network'
      preLoaderRoute: typeof SettingsDevelopmentNetworkRouteImport
      parentRoute: typeof SettingsDevelopmentRoute
    }
    '/settings/development/custom-chains': {
      id: '/settings/development/custom-chains'
      path: '/custom-chains'
      fullPath: '/settings/development/custom-chains'
      preLoaderRoute: typeof SettingsDevelopmentCustomChainsRouteImport
      parentRoute: typeof SettingsDevelopmentRoute
    }
    '/product/$id/{-$route}': {
      id: '/product/$id/{-$route}'
      path: '/product/$id/{-$route}'
      fullPath: '/product/$id/{-$route}'
      preLoaderRoute: typeof ProductIdChar123RouteChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy/permissions/': {
      id: '/settings/privacy/permissions/'
      path: '/privacy/permissions'
      fullPath: '/settings/privacy/permissions/'
      preLoaderRoute: typeof SettingsPrivacyPermissionsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy/apps/': {
      id: '/settings/privacy/apps/'
      path: '/privacy/apps'
      fullPath: '/settings/privacy/apps/'
      preLoaderRoute: typeof SettingsPrivacyAppsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy/permissions/$permissionId': {
      id: '/settings/privacy/permissions/$permissionId'
      path: '/privacy/permissions/$permissionId'
      fullPath: '/settings/privacy/permissions/$permissionId'
      preLoaderRoute: typeof SettingsPrivacyPermissionsPermissionIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy/apps/$productId': {
      id: '/settings/privacy/apps/$productId'
      path: '/privacy/apps/$productId'
      fullPath: '/settings/privacy/apps/$productId'
      preLoaderRoute: typeof SettingsPrivacyAppsProductIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy/permissions/$permissionId/': {
      id: '/settings/privacy/permissions/$permissionId/'
      path: '/'
      fullPath: '/settings/privacy/permissions/$permissionId/'
      preLoaderRoute: typeof SettingsPrivacyPermissionsPermissionIdIndexRouteImport
      parentRoute: typeof SettingsPrivacyPermissionsPermissionIdRoute
    }
    '/settings/privacy/apps/$productId/': {
      id: '/settings/privacy/apps/$productId/'
      path: '/'
      fullPath: '/settings/privacy/apps/$productId/'
      preLoaderRoute: typeof SettingsPrivacyAppsProductIdIndexRouteImport
      parentRoute: typeof SettingsPrivacyAppsProductIdRoute
    }
    '/settings/privacy/permissions/$permissionId/$productId': {
      id: '/settings/privacy/permissions/$permissionId/$productId'
      path: '/$productId'
      fullPath: '/settings/privacy/permissions/$permissionId/$productId'
      preLoaderRoute: typeof SettingsPrivacyPermissionsPermissionIdProductIdRouteImport
      parentRoute: typeof SettingsPrivacyPermissionsPermissionIdRoute
    }
    '/settings/privacy/apps/$productId/$permissionId': {
      id: '/settings/privacy/apps/$productId/$permissionId'
      path: '/$permissionId'
      fullPath: '/settings/privacy/apps/$productId/$permissionId'
      preLoaderRoute: typeof SettingsPrivacyAppsProductIdPermissionIdRouteImport
      parentRoute: typeof SettingsPrivacyAppsProductIdRoute
    }
  }
}

interface SettingsDevelopmentRouteChildren {
  SettingsDevelopmentCustomChainsRoute: typeof SettingsDevelopmentCustomChainsRoute
  SettingsDevelopmentNetworkRoute: typeof SettingsDevelopmentNetworkRoute
  SettingsDevelopmentUpdateChannelRoute: typeof SettingsDevelopmentUpdateChannelRoute
}

const SettingsDevelopmentRouteChildren: SettingsDevelopmentRouteChildren = {
  SettingsDevelopmentCustomChainsRoute: SettingsDevelopmentCustomChainsRoute,
  SettingsDevelopmentNetworkRoute: SettingsDevelopmentNetworkRoute,
  SettingsDevelopmentUpdateChannelRoute: SettingsDevelopmentUpdateChannelRoute,
}

const SettingsDevelopmentRouteWithChildren =
  SettingsDevelopmentRoute._addFileChildren(SettingsDevelopmentRouteChildren)

interface SettingsPrivacyAppsProductIdRouteChildren {
  SettingsPrivacyAppsProductIdPermissionIdRoute: typeof SettingsPrivacyAppsProductIdPermissionIdRoute
  SettingsPrivacyAppsProductIdIndexRoute: typeof SettingsPrivacyAppsProductIdIndexRoute
}

const SettingsPrivacyAppsProductIdRouteChildren: SettingsPrivacyAppsProductIdRouteChildren =
  {
    SettingsPrivacyAppsProductIdPermissionIdRoute:
      SettingsPrivacyAppsProductIdPermissionIdRoute,
    SettingsPrivacyAppsProductIdIndexRoute:
      SettingsPrivacyAppsProductIdIndexRoute,
  }

const SettingsPrivacyAppsProductIdRouteWithChildren =
  SettingsPrivacyAppsProductIdRoute._addFileChildren(
    SettingsPrivacyAppsProductIdRouteChildren,
  )

interface SettingsPrivacyPermissionsPermissionIdRouteChildren {
  SettingsPrivacyPermissionsPermissionIdProductIdRoute: typeof SettingsPrivacyPermissionsPermissionIdProductIdRoute
  SettingsPrivacyPermissionsPermissionIdIndexRoute: typeof SettingsPrivacyPermissionsPermissionIdIndexRoute
}

const SettingsPrivacyPermissionsPermissionIdRouteChildren: SettingsPrivacyPermissionsPermissionIdRouteChildren =
  {
    SettingsPrivacyPermissionsPermissionIdProductIdRoute:
      SettingsPrivacyPermissionsPermissionIdProductIdRoute,
    SettingsPrivacyPermissionsPermissionIdIndexRoute:
      SettingsPrivacyPermissionsPermissionIdIndexRoute,
  }

const SettingsPrivacyPermissionsPermissionIdRouteWithChildren =
  SettingsPrivacyPermissionsPermissionIdRoute._addFileChildren(
    SettingsPrivacyPermissionsPermissionIdRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDevelopmentRoute: typeof SettingsDevelopmentRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsPrivacyAppsProductIdRoute: typeof SettingsPrivacyAppsProductIdRouteWithChildren
  SettingsPrivacyPermissionsPermissionIdRoute: typeof SettingsPrivacyPermissionsPermissionIdRouteWithChildren
  SettingsPrivacyAppsIndexRoute: typeof SettingsPrivacyAppsIndexRoute
  SettingsPrivacyPermissionsIndexRoute: typeof SettingsPrivacyPermissionsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDevelopmentRoute: SettingsDevelopmentRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsPrivacyAppsProductIdRoute:
    SettingsPrivacyAppsProductIdRouteWithChildren,
  SettingsPrivacyPermissionsPermissionIdRoute:
    SettingsPrivacyPermissionsPermissionIdRouteWithChildren,
  SettingsPrivacyAppsIndexRoute: SettingsPrivacyAppsIndexRoute,
  SettingsPrivacyPermissionsIndexRoute: SettingsPrivacyPermissionsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChatChar123ChatIdChar125Route: ChatChar123ChatIdChar125Route,
  NewTabIdRoute: NewTabIdRoute,
  ProductIdChar123RouteChar125Route: ProductIdChar123RouteChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
